### ISSUE TITLE
Documentation & contributing

### ISSUE THREAD

**Issue by 0xCoto** [garrettj403/RF-tools#1]
Hi! This project looks quite interesting, judging by some notebooks I find on the repository. Is there any documentation available yet, or is it part of the to-do's? Also, are there any issues contributors could work on to help with the project?

On another note: regarding the [Cantenna notebook](https://github.com/garrettj403/RF-tools/blob/master/notebooks/Cantenna.ipynb), how is `min_height` derived exactly? I haven't really dug into the code to fully understand what `min_height[i] = 0.75 * 2 * sc.pi / wg.beta(fc, mode='TE11')` implies, but I would appreciate if you could point me to some reference explaining the formula. For example, what would happen if the height of a cylindrical waveguide is close to or less than the theoretical 'minimum height'? Would this significantly degrade e.g. the reflection coefficient, or just widen the beamwidth?

Cheers!

**Comment by garrettj403** [comment]
Hi @0xCoto, glad you find it interesting!

This repo is really just a dumping ground for my recurring RF-related code. Most of the functions are just transcribed directly out of Pozar.

I originally developed the `RF-tools` package because Scikit-RF wouldn't import the port impedance from HFSS-generated touchstone files (it always assumed Z0=50ohms), but they have since fixed this issue. Now, I just add new functions when I need them for my work. I don't currently have any plans to add anything, but again that depends on my work. If you feel that it's missing anything, feel free to create a new issue and add what you like!

Regarding the Cantenna notebook... `min_height` is just a general rule of thumb that you want your waveguide to be at least 0.75 * lambda. It's been a while since I worked on that. It should be in one of the references at the top of the notebook. 

I'm just guessing... but if your waveguide is very short, the waveguide probe will act more like a monopole antenna. If the waveguide is long, the higher-order/evanescent modes should die off and you'll only be left with the fundamental mode of the waveguide. This will affect your beam pattern. I can't tell you the exact effect without simulating the cantenna in something like HFSS.
